### ISSUE TITLE
Qt4 + webkit = crash

### ISSUE THREAD

**Issue by Shura0** [psi-plus/psi-plus-snapshots#15]
Привет.

Программа падает при попытке открыть окно чата:
```
W:QObject::connect: Cannot connect (null)::themeChanged() to ChatView::init()
[1]    24889 segmentation fault (core dumped)  ./psi-plus
```

Без webkit собирается и работает нормально.
Система Ubuntu
ibqt4-dev                                 4:4.8.7
ibqtwebkit-dev                       2.3.2

**Comment by Ri0n** [comment]
Надо удалить всё к чертям и сразу собирать только вебкит и заработает.

**Comment by rapgro** [comment]
Any plan to migrate to QtWebEngine?

**Comment by Ri0n** [comment]
in progress.

**Comment by Shura0** [comment]
Да, после полного удаления собралось и запустилось нормально.
Как-то можно удостовериться, что psi действительно использует webkit?

**Comment by Ri0n** [comment]
анимированные смайл паки работают. в контекстном меню на логе чата есть inspect

**Comment by tehnick** [comment]
Да, можно. Например:
* в настройках появится выбор темы оформления
* выбрать пакет с анимированными смайлами и воспользоваться ими в чате

**Comment by Shura0** [comment]
Да, работает!
Спасибо
