### ISSUE TITLE
Окно чата перемещение вкладок || Chat window: moving tabs 

### ISSUE THREAD

**Issue by Thoh2Phophuh** [psi-plus/psi-plus-snapshots#17]
Здравствуйте, раньше работало перемещение вкладок контактов в окне чата, где-то в районе версии 20140723, а в последних версиях 2016хххх перестало. Исправьте, пожалуйста.

Hello, it was possible to move the tabs in chat window before, somewhere around version 20140723, but in the last versions 2016xxxx it got broken. Please fix.

**Comment by tehnick** [comment]
https://github.com/psi-im/psi/issues
