### ISSUE TITLE
psi+ doesn't see otrplugin

### ISSUE THREAD

**Issue by modInfo** [psi-plus/psi-plus-snapshots#5]
I compiled successful the otr plugin from the current snapshot, copied to *path and psi+ does not see otrplugin..

*/usr/lib/psi-plus/plugins/libotrplugin.so
selink to /usr/lib64/psi-plus/plugins/libotrplugin.so, /lib/psi-plus/plugins/libotrplugin.so, /lib64/psi-plus/plugins/libotrplugin.so

**Comment by dirk-olmes** [comment]
Does it show up in Options -> Plugins or is that what you mean by psi does not see the plugin?

**Comment by wadealer** [comment]
Just put it to ~/.local/share/psi+/plugins

**Comment by modInfo** [comment]
dirk-olmes: exactly, the list of plug-ins are all plugins except otrplugin.
wadealer: also already tried, as in the INSTALL is written, does not show the plug
yes, I launched again psi+

**Comment by wadealer** [comment]
Please, update your version. Compile Psi+ from this snapshot repo. 130 is the very old version.

**Comment by modInfo** [comment]
wadealer: I have this problem when compiling https://bbs.archlinux.org/viewtopic.php?pid=1533971

**Comment by wadealer** [comment]
Please visit our conference. Any way, this issue has no relation to this repo. Closing.
